### ISSUE TITLE
Klipper does not start after upgrading to v0.10.0-88-gd90c3bc5

### ISSUE THREAD

**Issue by amertner** [Klipper3d/klipper#4854]
This is on an otherwise clean install of mainsailos: Install, run, upgrade. This is what shows up in syslog:

Oct 30 11:47:55 mainsailos systemd[1]: Started Starts Klipper and provides klippy Unix Domain Socket API.
Oct 30 11:47:55 mainsailos python[7030]: Traceback (most recent call last):
Oct 30 11:47:55 mainsailos python[7030]:   File "/home/pi/klipper/klippy/klippy.py", line 8, in <module>
Oct 30 11:47:55 mainsailos python[7030]:     import util, reactor, queuelogger, msgproto
Oct 30 11:47:55 mainsailos python[7030]:   File "/home/pi/klipper/klippy/reactor.py", line 59, in <module>
Oct 30 11:47:55 mainsailos python[7030]:     class ReactorGreenlet(greenlet.greenlet):
Oct 30 11:47:55 mainsailos python[7030]: AttributeError: 'module' object has no attribute 'greenlet'
Oct 30 11:47:55 mainsailos systemd[1]: klipper.service: Main process exited, code=exited, status=1/FAILURE

I have had a look, and it's not obvious what is wrong. The greenlet package is installed in the klippy env.

**Comment by amertner** [comment]
I did the update via mainsail, and it didn't pull all of the dependencies.

Running this fixed the issue:

`~/klippy-env/bin/pip install -r ~/klipper/scripts/klippy-requirements.txt
`
